### ISSUE TITLE
Add remaining test cases for TypeScript ported files in musicutils

### ISSUE THREAD

**Issue by meganindya** [sugarlabs/musicblocks-v4-lib#25]
On branch [`musicutils`](https://github.com/sugarlabs/musicblocks-v4-lib/tree/musicutils), there are `.test.ts` files corresponding to Python to TypeScript ported files.

However, the test cases aren't exhaustive &mdash; some cases aren't covered. Add missing test cases.

- [x] `scale.test.ts` #41
- [x] `musicUtils.test.ts` #29
- [x] `temperament.test.ts` #37
- [x] `keySignature.test.ts` #61
- [x] `currentPitch.test.ts`

**Comment by ricknjacky** [comment]
> * [ ]  `keySignature.test.ts` - improve on the organization and clarity of the tests

@meganindya what exactly are the deliverables here? I'd like to give a shot at this part of the issue.

**Comment by meganindya** [comment]
See the other test files to get an idea about the expected pattern. Mostly about separating and describing individual tests in words.
